version: '3.3'

services:
  web:
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data






  nginx:
     build:
       context: .
       dockerfile: nginx/Dockerfile
     ports:
       - "80:80"
     volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
     depends_on:
       - web

volumes:
  db_data:
  static_volume:
  media_volume: