# Generated by Django 5.0.2 on 2024-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационный блок',
                'indexes': [models.Index(fields=['id'], name='app_info_in_id_4e332b_idx'), models.Index(fields=['title'], name='app_info_in_title_687e08_idx')],
            },
        ),
    ]
