# Generated by Django 5.0.2 on 2024-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
