# Generated by Django 5.0.2 on 2024-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_baner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baner',
            name='image',
            field=models.ImageField(upload_to='baner/', verbose_name='Картинка Банера'),
        ),
    ]
